<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260129141210 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE amenity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, icon VARCHAR(50) NOT NULL, category VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, description TEXT NOT NULL, icon_url VARCHAR(500) NOT NULL, category VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, check_in_date DATE NOT NULL, check_out_date DATE NOT NULL, number_of_guests INT NOT NULL, number_of_nights INT NOT NULL, price_per_night NUMERIC(10, 2) NOT NULL, cleaning_fee NUMERIC(10, 2) NOT NULL, total_amount NUMERIC(10, 2) NOT NULL, booking_status VARCHAR(50) NOT NULL, payment_status VARCHAR(50) NOT NULL, payment_method VARCHAR(50) NOT NULL, special_requests TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, property_id INT NOT NULL, guest_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E00CEDDE549213EC ON booking (property_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDE9A4AA658 ON booking (guest_id)');
        $this->addSql('CREATE TABLE challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, description TEXT NOT NULL, challenge_type VARCHAR(50) NOT NULL, target_value INT NOT NULL, xp_reward INT NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message_text TEXT NOT NULL, is_read BOOLEAN NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, booking_id INT NOT NULL, sender_id INT NOT NULL, receiver_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F3301C60 ON message (booking_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FF624B39D ON message (sender_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FCD53EDB6 ON message (receiver_id)');
        $this->addSql('CREATE TABLE property (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, property_type VARCHAR(50) NOT NULL, address_line1 VARCHAR(255) NOT NULL, address_line2 VARCHAR(255) DEFAULT NULL, city VARCHAR(100) NOT NULL, state VARCHAR(100) DEFAULT NULL, country VARCHAR(100) NOT NULL, postal_code VARCHAR(20) NOT NULL, latitude NUMERIC(10, 8) NOT NULL, longitude NUMERIC(11, 8) NOT NULL, max_guests INT NOT NULL, bedrooms INT NOT NULL, beds INT NOT NULL, bathrooms NUMERIC(3, 1) NOT NULL, price_per_night NUMERIC(10, 2) NOT NULL, cleaning_fee NUMERIC(10, 2) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, host_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8BF21CDE1FB8D185 ON property (host_id)');
        $this->addSql('CREATE TABLE property_amenity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, property_id INT NOT NULL, amenity_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F2AD331B549213EC ON property_amenity (property_id)');
        $this->addSql('CREATE INDEX IDX_F2AD331B9F9F1305 ON property_amenity (amenity_id)');
        $this->addSql('CREATE TABLE property_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image_url VARCHAR(500) NOT NULL, is_primary BOOLEAN NOT NULL, display_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, property_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_32EC552549213EC ON property_image (property_id)');
        $this->addSql('CREATE TABLE property_view (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, viewed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, property_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E1E514B4A76ED395 ON property_view (user_id)');
        $this->addSql('CREATE INDEX IDX_E1E514B4549213EC ON property_view (property_id)');
        $this->addSql('CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, review_type VARCHAR(50) NOT NULL, rating NUMERIC(2, 1) NOT NULL, cleanliness_rating NUMERIC(2, 1) NOT NULL, accuracy_rating NUMERIC(2, 1) NOT NULL, communication_rating NUMERIC(2, 1) NOT NULL, location_rating NUMERIC(2, 1) NOT NULL, value_rating NUMERIC(2, 1) NOT NULL, comment TEXT DEFAULT NULL, is_visible BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, booking_id INT NOT NULL, reviewer_id INT NOT NULL, reviewee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_794381C63301C60 ON review (booking_id)');
        $this->addSql('CREATE INDEX IDX_794381C670574616 ON review (reviewer_id)');
        $this->addSql('CREATE INDEX IDX_794381C6BD992930 ON review (reviewee_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(20) NOT NULL, avatar_url VARCHAR(500) NOT NULL, bio TEXT DEFAULT NULL, is_host BOOLEAN NOT NULL, is_verified BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, earned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, badge_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1C32B345A76ED395 ON user_badge (user_id)');
        $this->addSql('CREATE INDEX IDX_1C32B345F7A2C2FC ON user_badge (badge_id)');
        $this->addSql('CREATE TABLE user_challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, current_progress INT NOT NULL, is_completed BOOLEAN NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, challenge_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D7E904B5A76ED395 ON user_challenge (user_id)');
        $this->addSql('CREATE INDEX IDX_D7E904B598A21AC6 ON user_challenge (challenge_id)');
        $this->addSql('CREATE TABLE user_gamification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level VARCHAR(50) NOT NULL, total_xp INT NOT NULL, current_streak_days INT NOT NULL, longest_streak_days INT NOT NULL, cities_explored_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2BFCB17DA76ED395 ON user_gamification (user_id)');
        $this->addSql('CREATE TABLE user_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, session_end TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration_seconds INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8849CBDEA76ED395 ON user_session (user_id)');
        $this->addSql('CREATE TABLE wishlist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, is_private BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9CE12A31A76ED395 ON wishlist (user_id)');
        $this->addSql('CREATE TABLE wishlist_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, added_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, wishlist_id INT NOT NULL, property_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6424F4E8FB8E54CD ON wishlist_item (wishlist_id)');
        $this->addSql('CREATE INDEX IDX_6424F4E8549213EC ON wishlist_item (property_id)');
        $this->addSql('CREATE TABLE xp_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, source_type VARCHAR(50) NOT NULL, source_id INT NOT NULL, description VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E526D970A76ED395 ON xp_transaction (user_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE549213EC FOREIGN KEY (property_id) REFERENCES property (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE9A4AA658 FOREIGN KEY (guest_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F3301C60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FCD53EDB6 FOREIGN KEY (receiver_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property ADD CONSTRAINT FK_8BF21CDE1FB8D185 FOREIGN KEY (host_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_amenity ADD CONSTRAINT FK_F2AD331B549213EC FOREIGN KEY (property_id) REFERENCES property (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_amenity ADD CONSTRAINT FK_F2AD331B9F9F1305 FOREIGN KEY (amenity_id) REFERENCES amenity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_image ADD CONSTRAINT FK_32EC552549213EC FOREIGN KEY (property_id) REFERENCES property (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_view ADD CONSTRAINT FK_E1E514B4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE property_view ADD CONSTRAINT FK_E1E514B4549213EC FOREIGN KEY (property_id) REFERENCES property (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C63301C60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C670574616 FOREIGN KEY (reviewer_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6BD992930 FOREIGN KEY (reviewee_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345F7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_challenge ADD CONSTRAINT FK_D7E904B5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_challenge ADD CONSTRAINT FK_D7E904B598A21AC6 FOREIGN KEY (challenge_id) REFERENCES challenge (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_gamification ADD CONSTRAINT FK_2BFCB17DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_session ADD CONSTRAINT FK_8849CBDEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wishlist ADD CONSTRAINT FK_9CE12A31A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wishlist_item ADD CONSTRAINT FK_6424F4E8FB8E54CD FOREIGN KEY (wishlist_id) REFERENCES wishlist (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wishlist_item ADD CONSTRAINT FK_6424F4E8549213EC FOREIGN KEY (property_id) REFERENCES property (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xp_transaction ADD CONSTRAINT FK_E526D970A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE549213EC');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE9A4AA658');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F3301C60');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FCD53EDB6');
        $this->addSql('ALTER TABLE property DROP CONSTRAINT FK_8BF21CDE1FB8D185');
        $this->addSql('ALTER TABLE property_amenity DROP CONSTRAINT FK_F2AD331B549213EC');
        $this->addSql('ALTER TABLE property_amenity DROP CONSTRAINT FK_F2AD331B9F9F1305');
        $this->addSql('ALTER TABLE property_image DROP CONSTRAINT FK_32EC552549213EC');
        $this->addSql('ALTER TABLE property_view DROP CONSTRAINT FK_E1E514B4A76ED395');
        $this->addSql('ALTER TABLE property_view DROP CONSTRAINT FK_E1E514B4549213EC');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C63301C60');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C670574616');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6BD992930');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_1C32B345A76ED395');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_1C32B345F7A2C2FC');
        $this->addSql('ALTER TABLE user_challenge DROP CONSTRAINT FK_D7E904B5A76ED395');
        $this->addSql('ALTER TABLE user_challenge DROP CONSTRAINT FK_D7E904B598A21AC6');
        $this->addSql('ALTER TABLE user_gamification DROP CONSTRAINT FK_2BFCB17DA76ED395');
        $this->addSql('ALTER TABLE user_session DROP CONSTRAINT FK_8849CBDEA76ED395');
        $this->addSql('ALTER TABLE wishlist DROP CONSTRAINT FK_9CE12A31A76ED395');
        $this->addSql('ALTER TABLE wishlist_item DROP CONSTRAINT FK_6424F4E8FB8E54CD');
        $this->addSql('ALTER TABLE wishlist_item DROP CONSTRAINT FK_6424F4E8549213EC');
        $this->addSql('ALTER TABLE xp_transaction DROP CONSTRAINT FK_E526D970A76ED395');
        $this->addSql('DROP TABLE amenity');
        $this->addSql('DROP TABLE badge');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE challenge');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE property');
        $this->addSql('DROP TABLE property_amenity');
        $this->addSql('DROP TABLE property_image');
        $this->addSql('DROP TABLE property_view');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_badge');
        $this->addSql('DROP TABLE user_challenge');
        $this->addSql('DROP TABLE user_gamification');
        $this->addSql('DROP TABLE user_session');
        $this->addSql('DROP TABLE wishlist');
        $this->addSql('DROP TABLE wishlist_item');
        $this->addSql('DROP TABLE xp_transaction');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
